apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-nginx
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
spec:
rules:
- host: 192.168.50.10
  http:
    paths:
    - path: "/"
      backend:
        serviceName: my-nginx
        servicePort: 8001